add_newline = false

[aws]
disabled = true
symbol = "î­ "

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[îŸ…](bold green)"

[directory]
truncation_length = 1

[ruby]
disabled = true
symbol = "î‘ "

[elixir]
disabled = true
symbol = "î˜­ "

[jobs]
disabled = true

[git_branch]
symbol = "îœ¥ "
format = "[$symbol$branch]($style) "
only_attached = true

[git_state]
rebase = ""
merge = "îœ§ "
revert = ""
cherry_pick = "ğŸ’ "

[git_status]
conflicted = "ğŸ’” "
ahead = "â¬†ï¸  "
behind = "â¬‡ï¸  "
staged = "ï‘— $count"
stashed = "ğŸ“¦ $count"
diverged = "ğŸ˜µ$count"
deleted = "ï‘˜ $count"
untracked = "ï„§ $count"
modified = "ï‘™ $count"
renamed = "ï‘š $count"

[line_break]
disabled = true

[nodejs]
disabled = true
symbol = "ï¢˜ "

[package]
disabled = true
symbol = "ğŸ”– "
