add_newline = false

[aws]
disabled = true
symbol = "î­ "

[character]
symbol = "$"

[directory]
truncation_length = 1

[elixir]
disabled = true
symbol = "î˜­ "

[jobs]
disabled = true

[git_branch]
symbol = "îœ¥ "

[git_state]
rebase = ""
merge = "îœ§ "
revert = ""
cherry_pick = "ğŸ’ "

[git_status]
conflicted = "ğŸ’” "
ahead = "â¬†ï¸  "
behind = "â¬‡ï¸  "
staged = "ï‘— "
staged_count.enabled = true
staged_count.style = "green"
stashed = "ğŸ“¦ "
stashed_count.enabled = true
diverged = "ğŸ˜µ"
deleted = "ï‘˜ "
deleted_count.enabled = true
untracked = "ï„§ "
untracked_count.enabled = true
modified = "ï‘™ "
modified_count.enabled = true
renamed = "ï‘š "
renamed_count.enabled = true

[line_break]
disabled = true

[nodejs]
disabled = true
symbol = "ï¢˜ "

[package]
disabled = true
symbol = "ğŸ”– "

[terraform]
show_version = true
